//! 系统剪贴板的读写。按 nspasteboard.org 的约定，密码管理器写入时会加标记类型，带标记的不读，也就不会上传。

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::NSString;

/// 带这些类型的条目不同步：密码（Concealed）、临时的（Transient）、程序自动生成的（AutoGenerated）。
const SKIP_TYPES: [&str; 3] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// 剪贴板当前的变更计数；每次有人写入都会变。
pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

/// 读当前的纯文本；没有文本、或带了不同步标记时返回 `None`。
pub fn read_text() -> Option<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    if let Some(types) = pasteboard.types() {
        let skip = types.iter().any(|t| {
            let t = t.to_string();
            SKIP_TYPES.contains(&t.as_str())
        });
        if skip {
            tracing::debug!("剪贴板带不同步标记，跳过");
            return None;
        }
    }
    let text = pasteboard.stringForType(unsafe { NSPasteboardTypeString })?;
    Some(text.to_string())
}

/// 写入纯文本，返回写入后的变更计数（调用方据此认出「这次是我写的」，不再上传回去）。
pub fn write_text(text: &str) -> isize {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.clearContents();
    pasteboard.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
    pasteboard.changeCount()
}
