//! 系统剪贴板的读写。按 nspasteboard.org 的约定，密码管理器写入时会加标记类型，带标记的不读，也就不会上传。

use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::NSString;

/// 带这些类型的条目不同步：密码（Concealed）、临时的（Transient）、程序自动生成的（AutoGenerated），
/// 以及苹果「通用剪贴板」从同一 Apple ID 的别的设备送来的（is-remote-clipboard）——那边的素笺云已经传过，
/// 这边再传就会和通用剪贴板互相回灌，两台 Mac 的剪贴板被来回改写。
const SKIP_TYPES: [&str; 4] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.apple.is-remote-clipboard",
];

/// 剪贴板当前的变更计数；每次有人写入都会变。
pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

/// 读当前的纯文本；没有文本、或带了不同步标记时返回 `None`。
pub fn read_text() -> Option<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    if let Some(types) = pasteboard.types() {
        let skip = types.iter().any(|t| {
            let t = t.to_string();
            SKIP_TYPES.contains(&t.as_str())
        });
        if skip {
            tracing::debug!("剪贴板带不同步标记，跳过");
            return None;
        }
    }
    let text = pasteboard.stringForType(unsafe { NSPasteboardTypeString })?;
    Some(text.to_string())
}

/// 当前条目是苹果「通用剪贴板」从别的设备送来的。只看类型，不读内容：读内容会让系统跨设备去取数据，主线程可能卡一两秒。
pub fn is_remote() -> bool {
    NSPasteboard::generalPasteboard()
        .types()
        .is_some_and(|types| {
            types
                .iter()
                .any(|t| t.to_string() == "com.apple.is-remote-clipboard")
        })
}

/// 当前的纯文本，不看标记（收到别的设备的内容时比对用：已经一样就不写，免得触发通用剪贴板再广播一次）。
/// 先用 [`is_remote`] 排除通用剪贴板送来的条目，那种不能在主线程上读。
pub fn current_text() -> Option<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    let text = pasteboard.stringForType(unsafe { NSPasteboardTypeString })?;
    Some(text.to_string())
}

/// 写入纯文本，返回写入后的变更计数（调用方据此认出「这次是我写的」，不再上传回去）。
pub fn write_text(text: &str) -> isize {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard.clearContents();
    pasteboard.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
    pasteboard.changeCount()
}
